# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'nwHackProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nwHackProject
pod 'immersive-reader-sdk', :git => 'https://github.com/microsoft/immersive-reader-sdk.git'
  target 'nwHackProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nwHackProjectUITests' do
    # Pods for testing
  end

end
